# Generated by Django 5.1.1 on 2024-09-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('restaurant_type', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('num_of_ratings', models.IntegerField()),
                ('avg_cost', models.FloatField()),
                ('online_order', models.CharField(max_length=10)),
                ('table_booking', models.CharField(max_length=10)),
                ('cuisines_type', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=200)),
                ('interaction_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
