# Generated by Django 5.1.1 on 2024-09-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_remove_usertable_password_remove_usertable_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='interaction_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
