# Generated by Django 5.1.1 on 2024-09-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
