# Generated by Django 5.1.1 on 2024-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_type', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0)),
                ('num_of_ratings', models.IntegerField(default=0)),
                ('avg_cost', models.FloatField(default=0)),
                ('online_order', models.BooleanField(default=False)),
                ('table_booking', models.BooleanField(default=False)),
                ('cuisines_type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('local_address', models.TextField()),
            ],
        ),
    ]
