# Generated by Django 5.1.1 on 2024-09-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
